import time
print ("The Twilight")
print ("Made By TokkPython Studios")
time.sleep(3)
print ("Press Enter To Start")
input ()
print ("They....")
time.sleep(2)
print ("They hijacked us...")
time.sleep(2)
print ("We can't do anything...\n")
time.sleep(2)
print ("Stranger: Hey! Are you ok?")
time.sleep(2)
print ("Stranger: Guys! Over here! Another survivor!\n")
time.sleep(2)
print ("But he rescued me...")
time.sleep(2)
print ("My best friend..\n")
time.sleep(2)
print ("Describer: There are 3 people around you.\nThere's a muscular man with a beard to the left of you. \nA woman, whos wiping your legs and hands carefully. \nAnother man to the right of you.")
time.sleep(2)
j1 = "Jake"
d1 = "Dennis"
c1 = "Clara"
print ("Muscular Stranger: My name is %s. This man is %s. And this my wife %s." % (j1,d1,c1))
time.sleep(2)
print ("Jake: We found you beside the pond, when the plane crashed")
time.sleep(2)
print ("Dennis: Hey.. we told you everything! Now, tell us your name.\n")
name1 = input ("Your Name Is: ")
print ("Dennis: %s eh? Welcome to the gang!" % (name1))
time.sleep(2)
print ("Clara: We can't just wait here and chat. It should be dark soon, lets get some resources")
time.sleep(2)
print ("Jake: Yeah, lets go %s"% (name1))
time.sleep(1)
print ("Get Resources For Your Gang!")
time.sleep(1)

print ("A: Get Wood\nB: Get Water\nC: Get Food")

